name: dartminer
version: 0.0.12

description: A Bitcoin miner with Dart language.
homepage: https://github.com/travist/dartminer

environment:
  sdk: '^3.0.0'
dependencies:
  convert: ^3.1.1
  crypto: 
  dio: ^5.1.2
  test: 
  # utf: 
